apiVersion: batch/v1
kind: Job
metadata:
  name: ltm
spec:
  template:
    spec:
      containers:
      - name: ltm
        image: byeongjokim/ltm:latest
        command: ["python",  "rund.py", "-b", "8", "--print-freq", "1", "-j", "4", "--dataset", "signd", "--datasetpath", "/data/AUTSL/train_img_c", "--pre", "", "--trainlist", "/data/AUTSL/train_p_fg_img_c/train_rgb_split01.txt", "--vallist", "/data/AUTSL/train_p_fg_img_c/val_rgb_split01.txt"]
        resources:
          limits:
            nvidia.com/gpu: 8
        volumeMounts:
        - mountPath: /data
          name: videos
        - mountPath: /dev/shm
          name: dshm
      restartPolicy: Never
      volumes:
      - name: videos
        hostPath:
          path: /nfs/vod_tag02/data
      - name: dshm
        emptyDir:
          medium: Memory
